### ISSUE TITLE
How to enable scroll left or right?

### ISSUE THREAD

**Issue by zero-edge-code** [kekc42/memorizing-pager#1]
With that I can change current page.

**Comment by imbeerus** [comment]
I don't think that is a good idea. 
The [Material Guide](https://material.io/guidelines/components/bottom-navigation.html) says:
**Bottom navigation** bars make it easy to explore and **switch** between top-level views **in a single tap**.

I didn't plan this feature and you'll need to make it possible with your own if you really want it
