### ISSUE TITLE
NavigationHistory class not being imported 

### ISSUE THREAD

**Issue by manu10** [kekc42/memorizing-pager#2]
After following the steps described in the Readme file to import the library I don't get the `NavigationHistory.java` file  under the `com.lockwood.memorizingpager` package, so I can't use the library.
Any idea what may be wrong?

**Comment by imbeerus** [comment]
Indeed ... Thanks for pointing out the error. Updated release, now there are no problems

Grab new version via Gradle:

```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```
```
dependencies {
    	implementation 'com.github.lndmflngs:memorizing-pager:2.0.1'
}
```
